### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by PacmanGraphics66** [Kas-tle/DL-beta-pack#1]
Hi, i saw no other way to contact you, so i send it to over here.

You might be interested in Minecraft NBT files and how to edit, because you took a look at the mca-nbt-edit.

In the Pacman-Graphics repo there is also another nbt system, used to load/save/change/create region files.

For an example of using this take a look at:

https://github.com/PacmanGraphics66/Pacman-Graphics/blob/master/PACMAN_CUBERITE/src/MCEditor/test.cpp

Result of this region file creator (example code):
https://www.youtube.com/watch?v=Q0EHdVRxQAs&list=PL-9ag_EiMQFkyRMaDy6G-otUxXEoXFtfM&index=16

The pacman graphics program is (one .exe) large collection of different c/c++ source codes.
If you need help setting things up, and/or extracting only the region file creator source msg me.
gerardwensink@gmail.com

**Comment by Kas-tle** [comment]
This is not an issue related to the resource pack.
